# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Workflow
on: 
  push: 
    branches: [master, main]
    
jobs: 
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: D3rHase/ssh-command-action@v0.2
      - name: connect
        with:
          HOST: l095r.ftp.infomaniak.com
          USER: l095r_andres
          PRIVATE_SSH_KEY: ${{ secrets.OMG_SECRET }}
          PASSWORD: ${{ secrets.PASSWORD }}    
