# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - name: Start SSH
      uses: Tofandel/ssh-server-action@v1.0.0
      with:
        hostname: l095r.ftp.infomaniak.com
        user_name: l095r_andres
        user_password: ${{ secrets.PASSWORD }} 
    - run: ls
